### ISSUE TITLE
Cannot find resource on Ubuntu 12.10

### ISSUE THREAD

**Issue by mb-dev** [markolson/chef-ssh#3]
NameError

---------

Cannot find a resource for ssh_known_hosts on ubuntu version 12.10

Cookbook Trace:
---------------
  /tmp/vagrant-chef/chef-solo-1/cookbooks/financeRails/recipes/default.rb:65:in `from_file'

Relevant File Content:
----------------------
/tmp/vagrant-chef/chef-solo-1/cookbooks/financeRails/recipes/default.rb:

--

I am getting the above error. And the stack trace points to my recipe containing:
ssh_known_hosts "github.com" do
  hashed true
  user app[:deploy_user]
end

So I am not sure where to look to debug this issue.

**Comment by fletchowns** [comment]
@tejaycar it's no longer an issue for me, I'm able to put ```depends 'ssh'``` in my metadata.rb and everything works as expected.

It's kinda confusing to have this old cookbook still out there though: https://supermarket.chef.io/cookbooks/ssh-util

Maybe put a note on it that it's deprecated? Or just remove it from the supermarket entirely?

**Comment by tejaycar** [comment]
@markolson He's got a good point.  Do you mind deprecating the `ssh-util` cookbook in favor of the `ssh` cookbook?

**Comment by mb-dev** [comment]
I am no longer playing with chef, so if you feel this is solved, feel free to close.
