### ISSUE TITLE
Newbies need Guidance on Persisting system updates between LWRPs

### ISSUE THREAD

**Issue by lonniev** [markolson/chef-ssh#31]
Although this should be better documented in the fundamental Chef documentation, the README.md here could mention the best tactics for accomplishing suitable synchronization of LWRPs in a recipe that needs to create new users and then create ssh configuration files for those new users.

Coming to Chef as a tyro, lacking a solid understanding of how Chef first accepts a specification for a change to system via a resource and then enqueues that specification for later execution, and with only a rudimentary understanding of how Chef's modularity is implemented, it can be a long trial and error process of getting a recipe for user creation, group assignment, sudo configuration, and ssh configuration to work in the presence of varying initial conditions. (The varying conditions include: total absence of anything in /etc/passwd, /etc/group, and /home for a particular user; presence of a partially constructed environment; presence of a malformed environment; and presence of a completely well-formed user environment.)

Currently, I have a manage-users recipe that seems to work for those use cases but I'm still just not sure how to program the LWRP statements so that I could definitely claim that their set could only execute with the particular execution order I intended.

The classic symptoms of out of order execution and of premature execution are exceptions thrown by Chef when the individual LWRPs find that entries in /etc/passwd are missing, that /home directories aren't in the filesystem to be the parent for subdirectories, and that various node attributes are nil. All these issues in temporal transitions resolve on subsequent chef runs. It would be far better to use notifications or ohai reloading or explicit coupling in the LWRPs to assure a particular order of execution and to flush queued changes to the actual target system.

Any advice on this?

**Comment by tejaycar** [comment]
Closing as this is more general chef documentation, and doesn't really belong in this cookbook specifically.  That said, I'm still open to a PR that explains the issues of concern.
