### ISSUE TITLE
resource.name is used for Host instead of resource.host

### ISSUE THREAD

**Issue by 5c077yP** [markolson/chef-ssh#39]
hey,

i'm working with version 0.10.2 and for the lwrp ssh_config it seems to use the name attribute for the Host instead of using the host attribute.

example:
```ruby
ssh_config 'github config for user root' do
  host 'github.com'
  options(
    'HostName' => 'github.com',
    'User' => 'git',
    'IdentityFile' => '/root/.ssh/id_rsa_github'
  )
end
```

creates the following:
```bash
$ cat /root/.ssh/config
# Created by Chef for tm-infrastructure-chef

Host github config for user root
  HostName github.com
  User git
  IdentityFile /root/.ssh/id_rsa_github
```

**Comment by tejaycar** [comment]
Yes, it sure does.  I'll get a fix out as quickly as I can.  Thanks for the catch

**Comment by 5c077yP** [comment]
wow, thanks for the quick response

**Comment by tejaycar** [comment]
Alright, it's released and on supermarket. Thanks again for spotting it.  Should have caught that in my tests, but I didn't have coverage.

**Comment by 5c077yP** [comment]
nice job, works perfectly!
