### ISSUE TITLE
Crash when directory .ssh does not exists

### ISSUE THREAD

**Issue by brauliobo** [markolson/chef-ssh#41]
I'm facing `Parent directory /var/backups/.ssh does not exist.` crash when the user doesn't have the `.ssh` directory. Should this cookbook create it?

**Comment by tejaycar** [comment]
For which resource?

**Comment by brauliobo** [comment]
@tejaycar, sorry, missed it, it is  `ssh_known_hosts`

**Comment by tejaycar** [comment]
So, it will create .ssh, but not the parent (/var/backups)

**Comment by brauliobo** [comment]
yeah, it is probably my mistake. closing this, thanks!
