### ISSUE TITLE
Missing View Source link on supermarket

### ISSUE THREAD

**Issue by fletchowns** [markolson/chef-ssh#46]
Most of the cookbooks have a "View Source" button that links back to the github repo, I don't see one for this cookbook though

https://supermarket.chef.io/cookbooks/ssh

**Comment by tejaycar** [comment]
Yea, if I had control of the cookbook on supermarket, I'd add the source, but I'm still working on getting that control back.

**Comment by tejaycar** [comment]
Fixed
