### ISSUE TITLE
Older version no longer available on supermarket?

### ISSUE THREAD

**Issue by fletchowns** [markolson/chef-ssh#47]
> Berkshelf::MissingLockfileCookbookVersion: Cookbook 'ssh' (0.10.5) not found in any of the sources! This can happen if the remote cookbook has been deleted or if the sources inside the Berksfile have changed. Please run `berks update ssh` to resolve to a valid version.

It seems as though versions older than 0.10.6 have been purged from supermarket. How come?

**Comment by tejaycar** [comment]
Yea, I was trying to remove a bad version from the supermarket, and it removed the whole cookbook.  Unfortunately, @mgoldsborough very quickly jumped in a claimed the cookbook name in supermarket, but uploaded only one version and no source link.  I actually have a new version now that includes authorized_keys as an LWRP, but I can't release it.  I'm working on getting in contact with the 'new' cookbook 'owner', but have not been able to reach him yet.

**Comment by fletchowns** [comment]
Ah bummer! Have you tried contacting the chef folks about it?

**Comment by tejaycar** [comment]
Yea, I'm working with them to get it resolved

**Comment by tejaycar** [comment]
fixed.  @fletchowns we've got several old releases out there now.  If the one you want is still missing, please let me know.

**Comment by fletchowns** [comment]
Awesome, thanks @tejaycar !
