### ISSUE TITLE
Default value TrueClass is invalid for property hashed of resource ssh_known_hosts.

### ISSUE THREAD

**Issue by CloCkWeRX** [markolson/chef-ssh#55]
```
  ssh
    git: https://github.com/markolson/chef-ssh.git
    revision: ca59ec5bf27ea9ed05d54a1d4304fd74b2ccc3f7
```

```
Deprecated features used!
  Default value TrueClass is invalid for property hashed of resource ssh_known_hosts. In Chef 13 this will become an error: Option hashed must be a kind of [TrueClass, FalseClass]!  You passed TrueClass.. at 1 location:
    - /tmp/chef/cookbooks/ssh/resources/known_hosts.rb:6:in `class_from_file'
```

**Comment by arosenhagen** [comment]
_In Chef 13 this will become an error_ so let's be kind to this ;-)

**Comment by tejaycar** [comment]
@arosenhagen  so what's the answer here?  A default value of `TrueClass` rather than `true`??

I find _Option hashed must be a kind of [TrueClass, FalseClass]!  You passed TrueClass_ to be clear as mud.  It's like saying, you must choose 1 or 2, but you chose 2.

**Comment by arosenhagen** [comment]
no, just like in the referenced commit:

```
attribute :hashed, :kind_of => [TrueClass, FalseClass], :default => true
```

**Comment by tejaycar** [comment]
Ah, I see.  Not sure how a default of TrueClass got in there in the first place.  I'll grab it in the next release.
