### ISSUE TITLE
Chef 13 fails while using lwrp ssh_authorized_keys

### ISSUE THREAD

**Issue by aalmenar** [markolson/chef-ssh#70]
Hi,

I ahve been using this nice cookbook for a long time, now i started testing my cookbooks with chef 13 and found the following problem:

NameError
           ---------
           uninitialized constant Chef::Resource::SshKnownHosts

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/ssh/providers/authorized_keys.rb:83:in `load_current_resource'
           /tmp/kitchen/cache/cookbooks/ssh/providers/authorized_keys.rb:76:in `initialize'

Regards.

**Comment by tejaycar** [comment]
Adrian,
I've not upgraded to chef 13 yet, so I'm not really familiar with the
breaking changes.  Do you have any notion of what caused this error, or how
to fix it?  I'd love a PR, but I can try to get the fix in myself if I have
some guidance.  But I just don't have time to troubleshoot from scratch at
this point.

Tejay

**Comment by aalmenar** [comment]
Hi Tejay,

There is a pull request compatible at least with chef 13 and chef 12.20.3 which are theones i tested it.
