### ISSUE TITLE
ssh_authorized_keys rejects public key

### ISSUE THREAD

**Issue by raviram203** [markolson/chef-ssh#72]
A very useful cookbook. Not sure I am using the authorized_keys function correctly.

`ssh_authorized_keys 'non-root authorized_keys' do`
`    user user_name`
`    key master_pub_key`
`    type 'ssh-rsa'`
` end`

fails with `does not match regular expression [/^\S*$/]`. The key contains:
`ssh-rsa AAAAB3NzaC....7eqMQiiJAQ==`. The invocation specifies `type 'ssh-rsa'`. Should the function process the key including `ssh-rsa`+space? I generated the pub key without the trailing comment (space + email) using `ssh-keygen -y -f ~/.ssh/master.id_rsa > ~/.ssh/master.id_rsa.pub`. I could not find options to strip the leading `ssh-rsa `.

Not sure you knew... The "Resources & Providers" section of the README is difficult to read in Chef Supermarket. I used Atom's markdown viewer.

**Comment by tejaycar** [comment]
the `key` field should only contain the key itself.  `ssh-rsa` goes in the `type` field and the trailing comment info can go into the `comments` field.  

As for the README, I'm happy to take any PR that would clean it up, but I'm not likely to get to it anytime soon myself.

**Comment by raviram203** [comment]
I tailored the pub key to suit `ssh_authorized_keys`. Will close this issue. Thank you for creating and sharing this tool. I could not find a command to generate the pub key without the leading "ssh-rsa ". So, I stripped it using sed:
`ssh-keygen -y -f  ~/.ssh/master.id_rsa | sed 's/ssh-rsa //' > /tmp/master_pub_key`
